apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevator-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elevator-api
  template:
    metadata:
      labels:
        app: elevator-api
    spec:
      containers:
      - name: elevator-api
        image: elevator-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: elevator-api
spec:
  selector:
    app: elevator-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
